KS-4-1 table
ILabzin/KotlinSprint pull request #18
Opened 2024-10-26 21:50 UTC by ILabzin

2024-10-27 06:08 UTC, ievetrovdev requested changes

2024-10-27 06:08 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson2_task2.kt
> +    println("Груз с весом $item1Weight кг и объемом $item1Capacity л соответствует категории 'Average': ${(item1Weight > averageWeightMin) && (item1Weight <= averageWeightMax) && (item1Capacity < ave
Да, код корректный. Но давай чуть улучшим.
Строки слишком длинные (>120 символов), глазу труднее в них ориентироваться. Часто в компаниях вводят правила форматирования, а также специальные утилиты, которые следят за соблюдением правил.

Вот например такая утилита Detekt для Kotlin запрещает по-умолчанию строки длиннее 120 символов: https://detekt.dev/docs/rules/formatting/#maximumlinelength.
Давай добавим перенос или вынесем в переменную условие

2024-10-27 13:00 UTC, ievetrovdev approved these changes

2024-10-27 13:00 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +                && (item1Weight <= averageWeightMax)
хоть и согласно https://kotlinlang.org/docs/coding-conventions.html конвенции нет строгих правил переноса длинных условия, на моей практике я везде встречал так: сначала на строке остается && / || , а затем строка переносится

2024-10-30 14:47 UTC, ILabzin commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +                && (item1Weight <= averageWeightMax)
Понял

2024-10-30 14:48 UTC, merged