KS-15-4 instrument and component
ILabzin/KotlinSprint pull request #71
Opened 2024-12-09 12:29 UTC by ILabzin

2024-12-09 20:33 UTC, ievetrovdev requested changes

2024-12-09 20:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task4.kt
> +) : SearchComponent
Все верно, но этот класс не должен реализовывать `SearchComponent` , это у нас базовый класс

2024-12-09 20:41 UTC, ILabzin commented on src/main/kotlin/lesson_15/lesson15_task4.kt
> +) : SearchComponent
да, я там увлекся реализациями и экспериментами разными, в итоге все упростил и удалил, а это забыл)

2024-12-10 20:21 UTC, ievetrovdev approved these changes

2024-12-11 08:09 UTC, merged