KS-5-6 IMT
ILabzin/KotlinSprint pull request #76
Opened 2024-12-09 21:00 UTC by ILabzin

2024-12-10 20:20 UTC, ievetrovdev requested changes

2024-12-10 20:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task6.kt
> +    when (imt) {
Давай сделаем еще проще, будем сразу присваивать значение:
`val result =  when (imt) `

2024-12-10 20:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task6.kt
> +    when (imt) {
Опечатка, ` result`

2024-12-12 17:33 UTC, ievetrovdev requested changes

2024-12-12 17:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task6.kt
> +    val result: String= when (imt) {
Напоминаю, все арифметические знаки обосабливаются пробелами.

В IDEA есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx). Рекомендую взять в привычку прожимать автоформат всегда перед коммитом, чтобы все отступы и пробелы расставить по своим местам.

2024-12-12 17:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task6.kt
> +        in 1.0..<18.0 ->  "недостаточная масса тела"
можно обойтись без диапазона используя imt < 18.5 и т.д

2024-12-19 19:57 UTC, ievetrovdev requested changes

2024-12-19 19:57 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task6.kt
> +    if (imt < 18.0) result = "недостаточная масса тела"
Давай оптимизируем и используем when

2024-12-20 14:52 UTC, ILabzin commented on src/main/kotlin/lesson_5/lesson5_task6.kt
> +    if (imt < 18.0) result = "недостаточная масса тела"
when не дает мне использовать выражение imt < 18.0. В первом варианте я использовал when c диапазонами. В интернете в основном все такие примеры. Я могу или сделать when с диапазонами или без диапазонов, но if

2024-12-21 13:26 UTC, ievetrovdev requested changes

2024-12-21 13:26 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task6.kt
> +    if (imt < 18.0) result = "недостаточная масса тела"
Хм, а почему не дает?

```
when {
        bmi < 18.5 -> "Недостаточная масса тела"
        bmi < 25 -> "Нормальная масса тела"
        bmi < 30 -> "Избыточная масса тела"
        else -> "Ожирение"
    }
```

2024-12-21 13:48 UTC, ILabzin commented on src/main/kotlin/lesson_5/lesson5_task6.kt
> +    if (imt < 18.0) result = "недостаточная масса тела"
when(imt) { - разобрался, вот в чем ошибка была, надо было аргумент убрать

2024-12-21 14:42 UTC, ievetrovdev approved these changes

2024-12-22 08:58 UTC, merged